// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/labstack/echo/v4"
	"orange-go/internal/api/healthcheck"
	"orange-go/internal/api/key"
	"orange-go/internal/storage/memory"
)

// Injectors from wire.go:

func InitializeHealthCheckAPI(e *echo.Echo) *healthcheck.API {
	api := healthcheck.NewAPI(e)
	return api
}

func InitializeKeyValueAPI(e *echo.Echo) *key.API {
	storage := memory.NewMemoryStorage()
	api := key.NewAPI(e, storage)
	return api
}
